fish_pr/apps/fish_app/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import auth_logout
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'fish_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('index5/', views.index5, name='index5'),

    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('registration/', views.registration, name='registration'),

    path('friends/', views.friends, name='friends'),
    path('messages/', views.messages, name='messages'),

    path('ihtio/', views.ihtio, name='ihtio'),

    path('pdetail<int:user_id>/', views.pdetail, name='pdetail'),

    path('get_profile_info/', views.get_profile_info, name='get_profile_info'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('add_request_for_friendship/', views.add_request_for_friendship, name='add_request_for_friendship'),
    path('add_to_friends/', views.add_to_friends, name='add_to_friends'),

    path('get_messages_from_room/', views.get_messages_from_room, name='get_messages_from_room'),
    path('send_message/', views.send_message, name='send_message'),

    path('get_places/', views.get_places, name='get_places'),
    path('get_place_info/', views.get_place_info, name='get_place_info'),
    path('add_place/', views.add_place, name='add_place'),
    path('delete_place/', views.delete_place, name='delete_place'),

    path('add_order/', views.add_order, name='add_order'),
    path('get_orders/', views.get_orders, name='get_orders'),
    path('get_order_info/', views.get_order_info, name='get_order_info'),
    path('delete_order/', views.delete_order, name='delete_order'),



    # path('change_profile/', views.change_profile, name='change_profile'),

    # path('<int:place_id>/leave_comment', views.leave_comment, name='leave_comment')
]

fish_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('fish_app/', include('fish_app.urls')),
    path('', include('fish_app.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fish_pr/apps/fish_app/forms.py
from django.forms import ModelForm
from .models import Profile
from django import forms


class AddPlaceForm(forms.Form):
    name = forms.CharField(label='Название места', max_length=100)
    lant = forms.DecimalField(label='Лантитуда', max_digits=10, decimal_places=8)
    long = forms.DecimalField(label='Лонгитуда', max_digits=10, decimal_places=8)
    description = forms.CharField(label='Описание',widget=forms.Textarea)
    is_Base = forms.BooleanField(label='База')
    car_accessibility = forms.BooleanField(label='Доступ на авто')
    bus_accessibility = forms.BooleanField(label='Доступ на общественном')

fish_pr/apps/fish_app/views.py
from django.shortcuts import render, redirect
from .models import FishingPlace, Profile, FishingPlaceImages, PlaceOrder, PlaceOrderImages, Friendship, Room, \
    UserMessage
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core import serializers
from django.forms.models import model_to_dict
from ftplib import FTP
from werkzeug.utils import secure_filename
import os
import copy
from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage, default_storage
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
import json
from datetime import datetime
from .forms import AddPlaceForm
import boto3
from django.db.models import Q
from itertools import chain


def index(request):
    is_logged = 0
    current_user_id = 0
    if request.user.is_authenticated:
        is_logged = 1
        try:
            current_user_id = request.session['userID']
        except:
            current_user_id = 0
    return render(request, 'fish_app/index.html', {'is_logged': is_logged, 'current_user_id': request.user.id})


def index5(request):
    return render(request, 'fish_app/index5.html')


def ihtio(request):
    return render(request, 'fish_app/ihtio.html')


def friends(request):
    curr_prof = Profile.objects.get(user_id=request.user.id)

    users_friends_id1 = Friendship.objects.filter(user_receiving=request.user.id, status='AC').values_list(
        'user_requesting')
    users_friends_id2 = Friendship.objects.filter(user_requesting=request.user.id, status='AC').values_list(
        'user_receiving')
    users_friends_id = chain(users_friends_id1, users_friends_id2)
    profiles_friends = Profile.objects.filter(user_id__in=users_friends_id)

    users_requesting_id = Friendship.objects.filter(user_receiving=request.user.id, status='WT').values_list(
        'user_requesting')
    profiles_requesting_friendship = Profile.objects.filter(user_id__in=users_requesting_id)

    users_receiving_id = Friendship.objects.filter(user_requesting=request.user.id, status='WT').values_list(
        'user_receiving')
    profiles_receiving_friendship = Profile.objects.filter(user_id__in=users_receiving_id)

    return render(request, 'fish_app/friends.html', {'profiles_friends': profiles_friends,
                                                     'profiles_requesting_friendship': profiles_requesting_friendship,
                                                     'profiles_receiving_friendship': profiles_receiving_friendship})


def messages(request):
    rooms = Room.objects.filter(users__id=request.user.id).order_by('-datetime_last_active')[:20]
    return render(request, 'fish_app/messages.html', {'rooms': rooms})


@csrf_exempt
def get_messages_from_room(request):
    try:
        r = Room.objects.get(id=request.POST.get("room_id"))
    except:
        raise Http404("Данные не найдены!..")
    try:
        room_messages = UserMessage.objects.filter(room=r).values().order_by('datetime_sending')
        chat_items = []
        last_message_user = 0
        chat_item = {}
        message = {}
        for mes in room_messages:
            if mes['user_send_id'] == last_message_user:  # append message to previous item
                message['time'] = mes['datetime_sending']
                message['content'] = mes['text']
                chat_items[-1]['messages'].append(copy.deepcopy(message))
            else:  # making new item - blok for messages from 1 sender
                last_message_user = mes['user_send_id']
                chat_item['photo_src'] = Profile.objects.filter(user_id=mes['user_send_id']).values('photo')[0]['photo']
                chat_item['user_send_id'] = mes['user_send_id']
                if mes['user_send_id'] == request.user.id:
                    chat_item['is_self'] = True
                else:
                    chat_item['is_self'] = False
                message['time'] = mes['datetime_sending']
                message['content'] = mes['text']
                chat_item['messages'] = []
                chat_item['messages'].append(copy.deepcopy(message))
                chat_items.append(copy.deepcopy(chat_item))
    except:
        kk = 'no messages'
    return JsonResponse(list(chat_items), safe=False)


@csrf_exempt
def send_message(request):
    if 'room_id' in request.POST:
        room = Room.objects.get(id=request.POST.get("room_id"))
        res = 1
    else:
        rooms = Room.objects.filter(users__id=request.user.id).filter(users__id=int(request.POST.get('user_id')))
        room = None
        for cur_room in rooms:
            if cur_room.users.all().count() == 2:
                room = cur_room
        if room is None:
            users = User.objects.filter(id__in=[request.user.id, int(request.POST.get('user_id'))])
            room = Room()
            room.save()
            for user in users:
                room.users.add(user)
        res = 2

    UserMessage(user_send=User.objects.get(id=request.user.id),
                room=room,
                text=request.POST.get("content")).save()
    return JsonResponse(res, safe=False)


@csrf_exempt
def add_request_for_friendship(request):
    res = 0

    if Friendship.objects.filter(user_requesting=User.objects.get(id=request.POST.get("receive_user_id")),
                                 user_receiving=User.objects.get(id=request.user.id)).exists():
        fr = Friendship.objects.filter(user_requesting=User.objects.get(id=request.POST.get("receive_user_id")),
                                       user_receiving=User.objects.get(id=request.user.id))
        fr.update(status='AC')
        res = 2
    elif Friendship.objects.filter(user_requesting=User.objects.get(id=request.user.id),
                                   user_receiving=User.objects.get(id=request.POST.get("receive_user_id"))).exists():
        res = 3
    else:
        Friendship.objects.create(user_requesting=User.objects.get(id=request.user.id),
                                  user_receiving=User.objects.get(id=request.POST.get("receive_user_id"))).save()
        res = 1

    return JsonResponse(res, safe=False)


@csrf_exempt
def add_to_friends(request):
    friendship = Friendship.objects.get(user_requesting=User.objects.get(id=int(request.POST.get("request_user_id"))),
                                        user_receiving=User.objects.get(id=int(request.user.id)))
    friendship.status = 'AC'
    friendship.save()

    return JsonResponse(1, safe=False)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            user_id = User.objects.get(username=user).id
            auth_login(request, user)
            request.session['userID'] = user_id
            return redirect('fish_app:index')
    else:
        form = AuthenticationForm()
    return 1


def logout(request):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('fish_app:index')
    return HttpResponse('fish_app:index')


def registration(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            user = User.objects.get(username=username)
            raw_password = form.cleaned_data.get('password1')
            profile = Profile(user=user)
            profile.save()
            return redirect('fish_app:index')
    else:
        form = UserCreationForm()
    return render(request, 'fish_app/registration.html', {'form': form})


def pdetail(request, user_id):
    try:
        p = Profile.objects.get(user_id=user_id)
    except:
        raise Http404("Данные не найдены!..")

    is_friends = False

    try:
        friendship1 = Friendship.objects.filter(user_requesting=user_id, user_receiving=int(request.user.id))
        friendship2 = Friendship.objects.filter(user_requesting=int(request.user.id), user_receiving=user_id)

        if len(friendship1) > 0:
            if friendship1[0].status == 'AC':
                is_friends = True
        if len(friendship2) > 0:
            if friendship2[0].status == 'AC':
                is_friends = True
    except:
        is_friends = False

    return render(request, 'fish_app/pdetail.html', {'profile': p, 'profile_user_id': user_id,
                                                     'is_friends': is_friends})


@csrf_exempt
def get_profile_info(request):
    user_id = request.POST.get('userID')
    user_by_id = User.objects.get(id=user_id)
    profile = Profile.objects.filter(user=user_by_id).values()
    return JsonResponse(list(profile), safe=False)


@csrf_exempt
def update_profile(request):
    uid = request.user.id
    us = User.objects.get(id=uid)
    current_profile = Profile.objects.get(user=us)
    type_info = request.POST.get("typeInfo")
    photo = request.FILES.getlist('profile_files')

    res = 0

    if type_info == 'main':
        current_profile.first_name = request.POST.get("first_name")
        current_profile.last_name = request.POST.get("last_name")

        current_profile.home_pond = request.POST.get("home_pond")
        current_profile.lovely_pond = request.POST.get("lovely_pond")
        current_profile.fishing_object = request.POST.get("fishing_object")
        current_profile.tackle = request.POST.get("tackle")

fish_pr/templates/fish_app/Profile_form.html
{% extends 'fish_app/base.html' %}

{% block title %} Edit Profile {% endblock %}

{% block content_area %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

fish_pr/templates/fish_app/_base.html
<!doctype html>
<html lang="en">
    <head>
        <title> {% block title %} My fishing site {% endblock %} </title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/lightbox.css' %}">
        {% block css_link %} {% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script type=text/javascript src="{% static 'js/libs/jquery-3.4.1.js' %}"></script>
        <script type=text/javascript src="{% static 'js/libs/lightbox.js' %}"></script>
        <script type=text/javascript src="{% static 'js/libs/bPopup.js' %}"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <script type=text/javascript src="{% static 'js/base.js' %}"></script>
        {% block js_link %} {% endblock %}

        <script type="text/javascript">
            currUserID = null;
            currPlaceID = null;
            currOrderID = null;
            myYandexMap = null;
            currProfile_json = "";

            $(document).ready(function() {

                currUserID = '{{ request.user.id }}';
                console.log('currUserID');
                console.log(currUserID);
                if (currUserID > 0) {

                    $('#profile_controlsID').show();
                    $('#login_formID').hide();
                    //reloadProfile();

                    lightbox.option({
                    'resizeDuration': 200,
                    'wrapAround': true
                    });


                } else {
                    $('#profile_controlsID').hide();
                    $('#login_formID').show();
                }

                {% block document_ready_script %} {% endblock %}

            });
        </script>


    </head>
    <body>

        <div class="container-fluid ">
        	<div class="row header">
        		<div class="col-md-12">
        			<ul class="nav">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownProfileMenuButtonID" data-toggle="dropdown"> Профиль </button>

                        <div class="dropdown-menu">
                            <div id="profile_controlsID">
                                <a class="dropdown-item" href="/pdetail{{ request.user.id }}">Мой профиль</a>
                                <a class="dropdown-item" href="/friends">Мои друзья</a>
                                <a class="dropdown-item" href="/messages">Мои сообщения</a>
                                <a class="dropdown-item" href="#">Мои отчеты</a>
                                <a class="dropdown-item" href="#">Мои рыбалки</a>
                                <a class="dropdown-item" href="#">Мои Трофеи</a>
                                <a class="dropdown-item" href="#">Мои объявления</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url "fish_app:logout" %}">Выйти</a>
                            </div>

                            <div id="login_formID" class="login_form">
                                <form role="form" action="{% url 'fish_app:login' %}" method="post" style="margin: 10px;" >
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_username">Имя пользователя</label>
                                        <input type="text" class="form-control" id="id_username" name="username" autocapitalize="none" autocomplete="username" maxlength="150" required/>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_password">Пароль</label>
                                        <input type="password" class="form-control" id="id_password" name="password" autocomplete="current-password" required/>
                                    </div>
                                    {% if request.GET.next %}
                                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                                    {% endif %}


                                    <button type="button" class="btn btn-link" onclick="location.href = '/registration';" >Регистрация</button>

                                    <button type="submit" class="btn btn-primary">Войти</button>
                                </form>
                            </div>

                        </div>

                        <li class="nav-item">
        					<a class="nav-link active" href="/">Карта</a>
        				</li>
        				<li class="nav-item">
        					<a class="nav-link active" href="#">Лента</a>
        				</li>
        				<li class="nav-item">
        					<a class="nav-link active" href="#">Ихтиосправочник</a>
        				</li>

        			</ul>
        		</div>
        	</div>
        	<div class="row">

        		<div class="col-md-12">
                    {% block working_area %}
                    {% endblock %}
        		</div>
        	</div>
        	<div class="row footer">
        		<div class="col-md-12">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link active" href="javascript: alert('Zenit SPb!')">Go</a>
                        </li>
                    </ul>
        		</div>
        	</div>
        </div>

        <div id="messageID" class="message">
            hello
        </div>

    </body>
</html>

fish_pr/templates/fish_app/_login.html
{% extends 'fish_app/base.html' %}

{% block title %} Log IN {% endblock %}

{% block css_link %}
{% endblock %}

{% block js_link %}
{% endblock %}

{% block js_script %} {% endblock %}

{% block working_area %}
    <h1> Log In!!!!! </h1>

    <form  method="post" >                 <!--  action="{% url 'fish_app:login' %}" -->
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <<input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>

    <p><a href="{% url 'fish_app:registration' %}">Registration</a></p>
{% endblock %}

fish_pr/templates/fish_app/chat.html
{% extends 'fish_app/base.html' %}

{% block title %} Chat #{{ chat.id }} {% endblock %}

{% block css_link %}
    {% load static %}

{% endblock %}

{% block js_link %}
    {% load static %}

{% endblock %}

{% block document_ready_script %}

{% endblock %}

{% block working_area %}
    {% for message in messages %}
        <!-- <a href="/pdetail{{ profile.user_id }}">{{ profile.first_name }}  {{ profile.last_name }}</a> <div class="active_caption"  id="add_to friends{{ profile.user_id }}ID" onclick="add_to_friends({{ profile.user_id }})">Добавить в друзья</div>       <br> -->
        #{{ chat.id }}_{{ message.datetime_sending }}_{{ message.user_send}}:{{ message.text }}   <br>
        <div class="">

        </div>
    {% endfor %}  <br>


{% endblock %}

fish_pr/templates/fish_app/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ place.name }} {% endblock %}

{% block content %}
    <h2>{{ place.name }}</h2>
    <p>{{ place.lant }}   {{ place.long }}</p>
    <p>{{ place.description }}</p>
    <em>{{ place.photos }}</em>
    <hr>
        {% if latest_order_list %}
            {% for o in latest_order_list %}
                <p>
                    <strong>{{ o.user_id }}</strong>
                    <p>{{ o.description }} </p>
                </p>
            {% endfor %}
        {% else %}
            Отчеты об этом месте не найдены
        {% endif %}
    <hr>

    <form action="{% url 'workspace:leave_comment' place.id %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="text" required placeholder="Ваше имя:" name="name"> <br>
        <textarea name="description" placeholder="Текст отчета:"></textarea> <br>

        <button type="submit" class="btn btn-success">Записать отчет></button>
    </form>

{% endblock %}

fish_pr/templates/fish_app/friends.html
{% extends 'fish_app/base.html' %}

{% block title %} Friends {% endblock %}

{% block css_link %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/friends.css' %}">
{% endblock %}

{% block js_link %}
    {% load static %}
    <script type=text/javascript src="{% static 'js/friends.js' %}"></script>
{% endblock %}

{% block document_ready_script %}
    openTab('friendsID')
{% endblock %}

{% block working_area %}

    <div class="tab">
      <button class="tablinks" onclick="openTab('friendsID')">Мои друзья</button>
      <button class="tablinks" onclick="openTab('receives_for_friendsID')">Входящие</button>
      <button class="tablinks" onclick="openTab('requests_for_friendsID')">Исходящие</button>
    </div>

    <div id="friendsID" class="tabcontent">
        <h4>Мои друзья:</h4>
        {% for profile in profiles_friends %}
            <a href="/pdetail{{ profile.user_id }}"><img src="http://fishkadata.s3.amazonaws.com/media/{{ profile.photo }}" alt="photo" class="friend-avatar"></a>

            <a href="/pdetail{{ profile.user_id }}">{{ profile.first_name }}  {{ profile.last_name }}</a>  <br>
        {% endfor %}  <br>
    </div>

    <div id="receives_for_friendsID" class="tabcontent">
        <h4>Входящие заявки в друзья:</h4>
        {% for profile in profiles_requesting_friendship %}
            <a href="/pdetail{{ profile.user_id }}">{{ profile.first_name }}  {{ profile.last_name }}</a> &nbsp;&nbsp;&nbsp;
            <a href="javascript:add_to_friends({{ profile.user_id }});" id="add_to friends{{ profile.user_id }}ID" class="activeButton">Добавить в друзья</a> <br>
            <!-- <div class="active_caption"  id="add_to friends{{ profile.user_id }}ID" onclick="add_to_friends({{ profile.user_id }})">Добавить в друзья</div> <br> -->
        {% endfor %}  <br>
    </div>

    <div id="requests_for_friendsID" class="tabcontent">
        <h4>Исходящие заявки в друзья:</h4>
        {% for profile in profiles_receiving_friendship %}
            <a href="/pdetail{{ profile.user_id }}">{{ profile.first_name }}  {{ profile.last_name }}</a> <br>
        {% endfor %}  <br>
    </div>

{% endblock %}

fish_pr/templates/fish_app/ihtio.html
{% extends 'fish_app/base.html' %}

{% block title %} Ихтиосправочник {% endblock %}

{% block css_link %}
    {% load static %}

{% endblock %}

{% block js_link %}
    {% load static %}


{% endblock %}

{% block document_ready_script %}


{% endblock %}

{% block working_area %}

    <div style="text-allign:center">
        Ихтиосправочник
    </div>

{% endblock %}

fish_pr/templates/fish_app/login.html
{% extends 'fish_app/base.html' %}

{% block title %} Log IN {% endblock %}

{% block css_link %}
{% endblock %}

{% block js_link %}
{% endblock %}

{% block js_script %} {% endblock %}

{% block working_area %}
    <h1> Log In!!!!! </h1>

    <form  method="post" >                 <!--  action="{% url 'fish_app:login' %}" -->
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <<input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>

    <p><a href="{% url 'fish_app:registration' %}">Registration</a></p>
{% endblock %}

fish_pr/templates/fish_app/messages.html
{% extends 'fish_app/base.html' %}

{% block title %} Мои сообщения {% endblock %}

{% block css_link %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/messages.css' %}">
{% endblock %}

{% block js_link %}
    {% load static %}
    <script type=text/javascript src="{% static 'js/messages.js' %}"></script>
{% endblock %}

{% block document_ready_script %}
    currRoomID = null;
{% endblock %}

{% block working_area %}
    <div class="message_content">
        <div class="rooms">
            {% for room in rooms %}
                {% if room.name != '' %}
                    <div class="active_caption"  id="room{{ room.id }}ID" onclick="load_mesages_from_room({{ room.id }})"> {{ room.name }} </div> <br>
                {% else %}
                    <div class="active_caption"  id="room{{ room.id }}ID" onclick="load_mesages_from_room({{ room.id }})"> Чат #{{ room.id }} </div> <br>
                {% endif %}
            {% endfor %}  <br>
        </div>
        <div id="messagesID" class="messages">
        </div>
        <div class="send_message">
            <br> <br>
            <input type="text" id="text_messageID">
            <input type="button" onclick="send_message();" value="Отправить">

        </div>

    </div>


{% endblock %}

fish_pr/templates/fish_app/registration.html
{% extends 'fish_app/base.html' %}

{% block css_link %}
    {% load static %}

{% endblock %}

{% block js_link %}


{% endblock %}

{% block title %} Регистрация {% endblock %}

{% block working_area %}
    <h1> Регистрация </h1>

    <form action="{% url 'fish_app:registration' %}" method="post" >
        {% csrf_token %}
        <label for="id_username">Имя пользователя:</label>
        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"> <br>
        <label for="id_password1">Пароль:</label>
        <input type="password" name="password1" autocomplete="new-password" required id="id_password1"> <br>
        <label for="id_password2">Подтверждение пароля:</label>
        <input type="password" name="password2" autocomplete="new-password" required id="id_password2"> <br>
        <input type="submit" value="Регистрация">
    </form>
{% endblock %}